apiVersion: v1
kind: Service
metadata:
  name: blockchain-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  selector:
    app: blockchain
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer
