apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-deployment
  labels:
    app: blockchain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain
  template:
    metadata:
      labels:
        app: blockchain
    spec:
      containers:
        - name: blockchain
          image: 399817749369.dkr.ecr.us-east-2.amazonaws.com/microservicio-blockchain:latest
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: blockchain-db-secret
